export class CustomerConstant {

    public static readonly COUNTRY_DATA = ["American", "British", "Canadian", "French", "German", "Italian", "Japanese", "Korean", "Mexican", "Russian", "Chinese", "Indian", "Australian", "Brazilian", "Swedish", "Spanish", "Dutch", "Argentinian", "Swiss", "Norwegian", "Irish", "Greek", "Turkish", "Egyptian", "South African", "Nigerian", "Pakistani", "Indonesian", "Thai", "Vietnamese", "Malaysian", "Portuguese", "Filipino", "Danish", "Finnish", "Belgian", "Austrian", "Israeli", "Iranian", "Iraqi", "Saudi Arabian", "Emirati", "Qatari", "Kuwaiti", "Omani", "Jordanian", "Lebanese", "Syrian", "Bangladeshi", "Sri Lankan", "Singaporean", "New Zealander", "Mexican", "Colombian", "Peruvian", "Chilean", "Venezuelan", "Costa Rican", "Guatemalan"];
    public static readonly IC_DATA = {Malaysian: ['MyKad (Malaysia Citizen)', 'MyTentera (Army in Services)', 'MyPR (Permananet Resident)', 'MyKas (Temporary Resident)', 'Others']};
    public static readonly SALUTATION_DATA = ["Dr", "Mdm", "Mr", "Mrs", "Ms", "Tan Sri", "Dato", "Datin", "Tengku", "Tuanku", "Prof"];

    public static readonly DIALING_CODE_DATA = [
        { value: "+1 (United States)", label: "+1 (United States)" },
        { value: "+44 (United Kingdom)", label: "+44 (United Kingdom)" },
        { value: "+1 (Canada)", label: "+1 (Canada)" },
        { value: "+33 (France)", label: "+33 (France)" },
        { value: "+49 (Germany)", label: "+49 (Germany)" },
        { value: "+39 (Italy)", label: "+39 (Italy)" },
        { value: "+81 (Japan)", label: "+81 (Japan)" },
        { value: "+82 (South Korea)", label: "+82 (South Korea)" },
        { value: "+52 (Mexico)", label: "+52 (Mexico)" },
        { value: "+7 (Russia)", label: "+7 (Russia)" },
        { value: "+86 (China)", label: "+86 (China)" },
        { value: "+91 (India)", label: "+91 (India)" },
        { value: "+61 (Australia)", label: "+61 (Australia)" },
        { value: "+55 (Brazil)", label: "+55 (Brazil)" },
        { value: "+46 (Sweden)", label: "+46 (Sweden)" },
        { value: "+34 (Spain)", label: "+34 (Spain)" },
        { value: "+31 (Netherlands)", label: "+31 (Netherlands)" },
        { value: "+54 (Argentina)", label: "+54 (Argentina)" },
        { value: "+41 (Switzerland)", label: "+41 (Switzerland)" },
        { value: "+47 (Norway)", label: "+47 (Norway)" },
        { value: "+353 (Ireland)", label: "+353 (Ireland)" },
        { value: "+30 (Greece)", label: "+30 (Greece)" },
        { value: "+90 (Turkey)", label: "+90 (Turkey)" },
        { value: "+20 (Egypt)", label: "+20 (Egypt)" },
        { value: "+27 (South Africa)", label: "+27 (South Africa)" },
        { value: "+234 (Nigeria)", label: "+234 (Nigeria)" },
        { value: "+92 (Pakistan)", label: "+92 (Pakistan)" },
        { value: "+62 (Indonesia)", label: "+62 (Indonesia)" },
        { value: "+66 (Thailand)", label: "+66 (Thailand)" },
        { value: "+84 (Vietnam)", label: "+84 (Vietnam)" },
        { value: "+60 (Malaysia)", label: "+60 (Malaysia)" },
        { value: "+351 (Portugal)", label: "+351 (Portugal)" },
        { value: "+63 (Philippines)", label: "+63 (Philippines)" },
        { value: "+45 (Denmark)", label: "+45 (Denmark)" },
        { value: "+358 (Finland)", label: "+358 (Finland)" },
        { value: "+32 (Belgium)", label: "+32 (Belgium)" },
        { value: "+43 (Austria)", label: "+43 (Austria)" },
        { value: "+972 (Israel)", label: "+972 (Israel)" },
        { value: "+98 (Iran)", label: "+98 (Iran)" },
        { value: "+964 (Iraq)", label: "+964 (Iraq)" },
        { value: "+966 (Saudi Arabia)", label: "+966 (Saudi Arabia)" },
        { value: "+971 (United Arab Emirates)", label: "+971 (United Arab Emirates)" },
        { value: "+974 (Qatar)", label: "+974 (Qatar)" },
        { value: "+965 (Kuwait)", label: "+965 (Kuwait)" },
        { value: "+968 (Oman)", label: "+968 (Oman)" },
        { value: "+962 (Jordan)", label: "+962 (Jordan)" },
        { value: "+961 (Lebanon)", label: "+961 (Lebanon)" },
        { value: "+963 (Syria)", label: "+963 (Syria)" },
        { value: "+880 (Bangladesh)", label: "+880 (Bangladesh)" },
        { value: "+94 (Sri Lanka)", label: "+94 (Sri Lanka)" },
        { value: "+65 (Singapore)", label: "+65 (Singapore)" },
        { value: "+64 (New Zealand)", label: "+64 (New Zealand)" },
        { value: "+52 (Mexico)", label: "+52 (Mexico)" },
        { value: "+57 (Colombia)", label: "+57 (Colombia)" },
        { value: "+51 (Peru)", label: "+51 (Peru)" },
        { value: "+56 (Chile)", label: "+56 (Chile)" },
        { value: "+58 (Venezuela)", label: "+58 (Venezuela)" },
        { value: "+506 (Costa Rica)", label: "+506 (Costa Rica)" },
        { value: "+502 (Guatemala)", label: "+502 (Guatemala)" }
    ];
}